### ISSUE TITLE
Abyssian big swing breaks bedrock

### ISSUE THREAD

**Issue by trantt214** [trantt214/GuildHallOrigins#29]
Big swing doesn't account for block hardness and pick tool

**Comment by Zyarch** [comment]
Current plan is to alter command so that it will only break blocks that are the same as the original block. Will update after testing when home.

**Comment by Zyarch** [comment]
Example:
/execute if blocks ~ ~ ~-1 ~ ~ ~-1 ~-1 ~ ~-1 all run fill ~ ~-1 ~-1 ~ ~-1 ~-1 minecraft:air destroy
Checks if a given block is the same as another block, and breaks it if so.
Command above functions in vanilla.

**Comment by Zyarch** [comment]
Abyssian big swing has changed, issue resolved.
